name: gestion_t
description: "ToDo App for Gestion T"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
